default_remote: mac
search_config:
- --exclude-dir="/build/*"
- --exclude-dir="/.git/*"
- --exclude-dir="/doc/*"
- --exclude-dir="/docs/*"
- --exclude-dir="/patches/*"
- --exclude-dir="/r/*"
- --exclude-dir="/tools/*"
- --exclude-dir="/Default/*"
- --exclude="tags"
- --exclude="*.json"
- --exclude="*.swp"
- --exclude-dir="/__pycache__/*"
- --exclude="*.log"
- --exclude-dir="/node-v*"
- --exclude-dir="/BrowserMetrics*"
terminal_abbreviate:
- - proxy
  - 'export http_proxy=http://172.19.57.45:3128

    export https_proxy=http://172.19.57.45:3128

    export no_proxy=localhost,bj.bcebos.com,su.bcebos.com,paddle-wheel.bj.bcebos.com

    '
- - build cinn
  - make -j32 paddle && cp -y libcinnapi.so ./python/paddle/libs/libcinnapi.so
- - run transpose
  - PYTHONPATH=/home/ssd2/xiongkun/Paddle/build/python/ python ../unittest1.py TestTrivalFusion.test_trival_fusion_tranpose
- - run rope
  - PYTHONPATH=/home/ssd2/xiongkun/Paddle/build/python/ python ../unittest1.py TestRotaryPosEmb
- - run subgraph
  - runhaskell ./mytests/run_all.hs ./mytests/test_sub_graph_12.py
- - run llama
  - cd /home/ssd2/xiongkun/PaddleNLP && bash run.sh
- - run llama profile
  - cd /home/ssd2/xiongkun/PaddleNLP && /opt/nvidia/nsight-systems/2022.4.1/bin/nsys profile --stats true -w true -t cuda,nvtx,osrt,cudnn,cublas bash run.sh